import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { Shield, Trash2, Download, EyeOff, Loader2, Key } from 'lucide-react'
import toast from 'react-hot-toast'
import { useNavigate } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import { deleteAccount as deleteAccountApi } from '../../services/settingsService'
import { getTasks } from '../../services/taskService'
import { getGoals } from '../../services/goalService'
import { getHabits } from '../../services/habitService'
// Account management with data export (PDF), clear data, and delete account options
function AccountSettings() {
  const { logout } = useAuth()
  const navigate = useNavigate()
  const [confirmDelete, setConfirmDelete] = useState(false)
  const [deletePassword, setDeletePassword] = useState('')
  const [deleting, setDeleting] = useState(false)
  const [exporting, setExporting] = useState(false)

  const handleExport = async () => {
    setExporting(true)
    try {
      const [tasks, goals, habits] = await Promise.all([
        getTasks().catch(() => []),
        getGoals().catch(() => []),
        getHabits().catch(() => []),
      ])
      const focusSessions = parseInt(localStorage.getItem('flowsync_focus_sessions') || '0')
      const focusMinutes = parseInt(localStorage.getItem('flowsync_focus_minutes') || '0')
      const date = new Date().toISOString().split('T')[0]

      const doc = new jsPDF()
      const pageW = doc.internal.pageSize.getWidth()
      let y = 20

      const title = (text, size = 16) => { doc.setFontSize(size); doc.text(text, pageW / 2, y, { align: 'center' }); y += 8 }
      const subtitle = (text) => { doc.setFontSize(10); doc.setTextColor(100); doc.text(text, pageW / 2, y, { align: 'center' }); y += 6; doc.setTextColor(0) }
      const section = (text) => { doc.setFontSize(12); doc.setFont(undefined, 'bold'); y += 4; doc.text(text, 14, y); y += 6; doc.setFont(undefined, 'normal') }
      const row = (label, value) => { doc.setFontSize(10); doc.text(label, 20, y); doc.text(String(value), 70, y); y += 5 }
      const tableHead = (cols, widths) => { doc.setFontSize(9); doc.setFont(undefined, 'bold'); let x = 14; cols.forEach((c, i) => { doc.text(c, x, y); x += widths[i] }); y += 5; doc.setFont(undefined, 'normal') }
      const tableRow = (vals, widths) => { doc.setFontSize(8); let x = 14; vals.forEach((v, i) => { doc.text(String(v).slice(0, 25), x, y); x += widths[i] }); y += 4 }

      title('FlowSync AI - Data Export', 18)
      subtitle(`Exported on ${date}`)

      // Overview
      section('Overview')
      row('Total Tasks', tasks.length)
      row('Total Goals', goals.length)
      row('Total Habits', habits.length)
      row('Focus Sessions', focusSessions)
      row('Focus Minutes', focusMinutes)
      const doneTasks = tasks.filter(t => t.status === 'done').length
      row('Completed Tasks', doneTasks)
      row('Completion Rate', tasks.length ? `${Math.round((doneTasks / tasks.length) * 100)}%` : '0%')

      // Tasks
      if (tasks.length > 0) {
        if (y > 240) { doc.addPage(); y = 20 }
        section('Tasks')
        const tWidths = [70, 20, 20, 30]
        tableHead(['Title', 'Priority', 'Status', 'Deadline'], tWidths)
        tasks.forEach(t => { if (y > 270) { doc.addPage(); y = 20 }; tableRow([t.title || '', t.priority || '', t.status || '', t.deadline ? new Date(t.deadline).toLocaleDateString() : ''], tWidths) })
      }

      // Goals
      if (goals.length > 0) {
        if (y > 240) { doc.addPage(); y = 20 }
        section('Goals')
        const gWidths = [70, 20, 30]
        tableHead(['Title', 'Status', 'Target Date'], gWidths)
        goals.forEach(g => { if (y > 270) { doc.addPage(); y = 20 }; tableRow([g.title || '', g.status || '', g.targetDate ? new Date(g.targetDate).toLocaleDateString() : ''], gWidths) })
      }

      // Habits
      if (habits.length > 0) {
        if (y > 240) { doc.addPage(); y = 20 }
        section('Habits')
        const hWidths = [70, 30, 20]
        tableHead(['Title', 'Frequency', 'Streak'], hWidths)
        habits.forEach(h => { if (y > 270) { doc.addPage(); y = 20 }; tableRow([h.title || '', h.frequency || '', String(h.streak || 0)], hWidths) })
      }

      // Footer
      doc.setFontSize(8); doc.setTextColor(150)
      doc.text('Generated by FlowSync AI', pageW / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

      doc.save(`flowsync_export_${date}.pdf`)
      toast.success('PDF exported successfully')
    } catch {
      toast.error('Failed to export PDF')
    } finally {
      setExporting(false)
    }
  }

  const handleClearData = () => {
    const keys = ['flowsync_tasks', 'flowsync_goals', 'flowsync_habits', 'flowsync_notifications', 'flowsync_focus_sessions', 'flowsync_focus_minutes']
    keys.forEach(k => localStorage.removeItem(k))
    toast.success('All data cleared')
  }

  const handleDeleteAccount = async () => {
    if (!deletePassword) { toast.error('Enter your password to confirm deletion'); return }
    setDeleting(true)
    try {
      await deleteAccountApi({ password: deletePassword })
      toast.success('Account deleted')
      logout()
      navigate('/')
    } catch (err) {
      toast.error(err?.response?.data?.message || 'Failed to delete account')
    } finally {
      setDeleting(false)
    }
  }

  const handleLogoutAll = () => {
    toast.success('Logged out of all devices (demo)')
  }

  return (
    <div className="space-y-6">
      <div className="bg-white dark:bg-zinc-900 rounded-2xl border border-slate-200 dark:border-zinc-800 shadow-sm p-6">
        <div className="flex items-center gap-2 mb-5">
          <div className="w-8 h-8 rounded-lg bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center">
            <Download size={16} className="text-indigo-600 dark:text-indigo-400" />
          </div>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Data & Privacy</h2>
        </div>

        <div className="space-y-3">
          <button onClick={handleExport} disabled={exporting} className="w-full flex items-center justify-between px-4 py-3 rounded-xl hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors disabled:opacity-60">
            <div className="flex items-center gap-3">
              <div className="w-7 h-7 rounded-lg bg-slate-100 dark:bg-zinc-800 flex items-center justify-center">
                {exporting ? <Loader2 size={13} className="text-indigo-500 animate-spin" /> : <Download size={13} className="text-slate-500" />}
              </div>
              <div className="text-left">
                <p className="text-sm font-medium text-slate-700 dark:text-slate-300">{exporting ? 'Exporting...' : 'Export Data'}</p>
                <p className="text-[10px] text-slate-500 dark:text-slate-400">Download your tasks, goals & habits as PDF</p>
              </div>
            </div>
            <span className="text-xs text-slate-400">&rarr;</span>
          </button>

          <button onClick={handleLogoutAll} className="w-full flex items-center justify-between px-4 py-3 rounded-xl hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors">
            <div className="flex items-center gap-3">
              <div className="w-7 h-7 rounded-lg bg-slate-100 dark:bg-zinc-800 flex items-center justify-center">
                <EyeOff size={13} className="text-slate-500" />
              </div>
              <div className="text-left">
                <p className="text-sm font-medium text-slate-700 dark:text-slate-300">Logout All Devices</p>
                <p className="text-[10px] text-slate-500 dark:text-slate-400">Sign out everywhere except this device</p>
              </div>
            </div>
            <span className="text-xs text-slate-400">&rarr;</span>
          </button>
        </div>
      </div>

      <div className="bg-white dark:bg-zinc-900 rounded-2xl border border-red-200 dark:border-red-900/50 shadow-sm p-6">
        <div className="flex items-center gap-2 mb-5">
          <div className="w-8 h-8 rounded-lg bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
            <Shield size={16} className="text-red-600 dark:text-red-400" />
          </div>
          <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Danger Zone</h2>
        </div>

        <div className="space-y-3">
          <button onClick={handleClearData} className="w-full flex items-center justify-between px-4 py-3 rounded-xl hover:bg-red-50 dark:hover:bg-red-900/10 transition-colors border border-red-100 dark:border-red-900/30">
            <div className="flex items-center gap-3">
              <div className="w-7 h-7 rounded-lg bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                <Trash2 size={13} className="text-red-500" />
              </div>
              <div className="text-left">
                <p className="text-sm font-medium text-red-700 dark:text-red-300">Clear All Data</p>
                <p className="text-[10px] text-red-500 dark:text-red-400">Remove all app data from this browser</p>
              </div>
            </div>
            <span className="text-xs text-red-400">&rarr;</span>
          </button>

          {!confirmDelete ? (
            <button onClick={() => setConfirmDelete(true)} className="w-full flex items-center justify-between px-4 py-3 rounded-xl hover:bg-red-50 dark:hover:bg-red-900/10 transition-colors border border-red-100 dark:border-red-900/30">
              <div className="flex items-center gap-3">
                <div className="w-7 h-7 rounded-lg bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                  <Trash2 size={13} className="text-red-500" />
                </div>
                <div className="text-left">
                  <p className="text-sm font-medium text-red-700 dark:text-red-300">Delete Account</p>
                  <p className="text-[10px] text-red-500 dark:text-red-400">Permanently delete your account and all data</p>
                </div>
              </div>
              <span className="text-xs text-red-400">&rarr;</span>
            </button>
          ) : (
            <div className="p-4 rounded-xl bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-900/50">
              <p className="text-sm font-medium text-red-700 dark:text-red-300 mb-3">This action cannot be undone.</p>
              <div className="flex items-center gap-2 mb-3">
                <Key size={14} className="text-red-500 flex-shrink-0" />
                <input
                  type="password"
                  value={deletePassword}
                  onChange={e => setDeletePassword(e.target.value)}
                  placeholder="Enter your password to confirm"
                  className="flex-1 px-3 py-2 rounded-lg border border-red-200 dark:border-red-900/50 bg-white dark:bg-zinc-900 text-sm text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-red-500"
                />
              </div>
              <div className="flex gap-2">
                <button onClick={handleDeleteAccount} disabled={deleting || !deletePassword} className="px-4 py-2 bg-red-600 text-white rounded-xl text-sm font-medium hover:bg-red-700 transition-colors disabled:opacity-50 flex items-center gap-1.5">
                  {deleting && <Loader2 size={13} className="animate-spin" />}
                  {deleting ? 'Deleting...' : 'Yes, delete my account'}
                </button>
                <button onClick={() => { setConfirmDelete(false); setDeletePassword('') }} className="px-4 py-2 bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-slate-300 rounded-xl text-sm font-medium hover:bg-slate-200 dark:hover:bg-zinc-700 transition-colors">Cancel</button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default AccountSettings
