import { useState } from 'react'
import { Brain } from 'lucide-react'
import PromptInput from './PromptInput'
import AIResult from './AIResult'
import RescueMode from './RescueMode'

function generatePlan(prompt) {
  const hasExam = /exam|test|quiz|assessment/i.test(prompt)
  const hasAssignment = /assignment|project|homework|paper|essay/i.test(prompt)
  const hasDeadline = /deadline|due|tomorrow|today|urgent|emergency/i.test(prompt)
  const hasMultiple = /\d+/.test(prompt) || /multiple|several|two|three|four|five/i.test(prompt)
  const urgency = hasDeadline ? 'high' : hasExam ? 'high' : hasAssignment ? 'medium' : 'low'
  const isEmergency = urgency === 'high' && (hasExam || hasMultiple)

  const tasks = []
  if (hasExam) tasks.push({ task: 'Exam Preparation', level: 'High', risk: 85, reason: 'Exam is time-sensitive with fixed schedule', duration: '3h', timeSlot: '09:00' })
  if (hasAssignment) tasks.push({ task: hasAssignment ? prompt.match(/assignment\s+(.+?)(?:and|\.|$)/i)?.[1]?.trim() || 'Assignment Work' : 'Assignment Work', level: hasDeadline ? 'High' : 'Medium', risk: hasDeadline ? 75 : 45, reason: hasDeadline ? 'Deadline approaching soon' : 'Moderate priority with flexible timeline', duration: '2h', timeSlot: hasExam ? '13:00' : '09:00' })
  if (hasMultiple && !hasExam && !hasAssignment) tasks.push({ task: 'Multiple Task Review', level: 'Medium', risk: 55, reason: 'Several tasks need organization and prioritization', duration: '1h', timeSlot: '09:00' })
  if (tasks.length === 0) {
    tasks.push({ task: 'General Planning', level: 'Low', risk: 20, reason: 'No urgent deadlines detected — focus on proactive work', duration: '1h', timeSlot: '09:00' })
  }

  const suggestions = []
  if (urgency === 'high') suggestions.push('Start with the highest-risk task immediately to avoid deadline pressure')
  if (hasExam) suggestions.push('Block 3+ hours for exam prep with no interruptions — enable Focus Mode')
  if (hasAssignment) suggestions.push('Break the assignment into research, outline, and writing phases')
  if (hasMultiple) suggestions.push('Group similar tasks together to reduce context switching')
  suggestions.push('Take a 15-minute break after every 2 hours of deep work')
  if (suggestions.length > 4) suggestions.pop()

  const schedule = []
  let currentTime = 9
  tasks.forEach(t => {
    const hours = parseInt(t.duration)
    const start = `${String(currentTime).padStart(2, '0')}:00`
    currentTime += hours
    const end = `${String(currentTime).padStart(2, '0')}:00`
    schedule.push({ time: start, task: t.task, duration: t.duration, end })
    if (currentTime < 18 && t !== tasks[tasks.length - 1]) {
      schedule.push({ time: `${String(currentTime).padStart(2, '0')}:00`, task: 'Short Break', duration: '15m', end: `${String(currentTime).padStart(2, '0')}:15` })
      currentTime += 0.25
    }
  })

  return { priority: tasks, schedule, suggestions, confidence: isEmergency ? 96 : urgency === 'high' ? 92 : 85, isEmergency, riskLevel: urgency === 'high' ? Math.max(...tasks.map(t => t.risk)) : 35 }
}

function AIPlanner() {
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [prompt, setPrompt] = useState('')

  const handleGenerate = (text) => {
    setPrompt(text)
    setLoading(true)
    setTimeout(() => {
      const plan = generatePlan(text)
      setResult(plan)
      setLoading(false)
    }, 1500)
  }

  const handleReset = () => {
    setResult(null)
    setPrompt('')
  }

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="flex items-center gap-3 mb-2">
        <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-900/40 flex items-center justify-center">
          <Brain size={22} className="text-indigo-600 dark:text-indigo-400" />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100">AI Planner</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">Turn chaos into a structured execution plan</p>
        </div>
      </div>

      {!result ? (
        <div className="mt-8 max-w-3xl mx-auto">
          <PromptInput onGenerate={handleGenerate} loading={loading} />
        </div>
      ) : (
        <div className="mt-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 px-3 py-1.5 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 rounded-full text-xs font-medium">
                <Brain size={12} /> Generated by FlowSync AI
              </div>
              <div className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 rounded-full text-xs font-medium">
                {result.confidence}% Confidence
              </div>
            </div>
            <button onClick={handleReset} className="text-sm text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300 transition-colors duration-300">
              New Plan
            </button>
          </div>

          <div className="grid lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
              <AIResult result={result} />
              <ExportPlan result={result} prompt={prompt} />
            </div>
            <div className="space-y-6">
              <RescueMode result={result} />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default AIPlanner
