import { useState } from 'react'
import { FileText, Clipboard, Save, Check } from 'lucide-react'
import toast from 'react-hot-toast'

function ExportPlan({ result, prompt }) {
  const [copying, setCopying] = useState(false)
  const [saving, setSaving] = useState(false)

  const buildPlanText = () => {
    let text = `AI Generated Plan — FlowSync AI\n`
    text += `Prompt: "${prompt}"\n`
    text += `Confidence: ${result.confidence}%\n\n`

    text += `=== PRIORITY ===\n`
    result.priority.forEach(t => {
      text += `[${t.level}] ${t.task} — ${t.reason} (Risk: ${t.risk}%)\n`
    })

    text += `\n=== SCHEDULE ===\n`
    result.schedule.forEach(s => {
      text += `${s.time} — ${s.task} (${s.duration})\n`
    })

    text += `\n=== SUGGESTIONS ===\n`
    result.suggestions.forEach(s => text += `• ${s}\n`)

    if (result.isEmergency) {
      text += `\n⚠️ EMERGENCY MODE ACTIVATED\n`
      text += `Focus only on critical tasks.\n`
    }

    text += `\nGenerated by FlowSync AI`
    return text
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(buildPlanText())
    setCopying(true)
    toast.success('Plan copied to clipboard')
    setTimeout(() => setCopying(false), 2000)
  }

  const handleSave = () => {
    const plans = JSON.parse(localStorage.getItem('flowsync_plans') || '[]')
    plans.push({ id: Date.now().toString(), prompt, result, createdAt: new Date().toISOString() })
    localStorage.setItem('flowsync_plans', JSON.stringify(plans))
    setSaving(true)
    toast.success('Plan saved to dashboard')
    setTimeout(() => setSaving(false), 2000)
  }

  const handlePdf = () => {
    const text = buildPlanText()
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `flowsync-plan-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Plan downloaded')
  }

  return (
    <div className="bg-white dark:bg-zinc-900 rounded-2xl border border-slate-200 dark:border-zinc-800 shadow-sm p-5">
      <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100 mb-4">Export Plan</h3>
      <div className="flex flex-wrap gap-3">
        <button onClick={handlePdf} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600 text-white text-sm font-medium transition-colors duration-300">
          <FileText size={16} /> Export PDF
        </button>
        <button onClick={handleCopy} className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-300 dark:border-zinc-700 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-100 dark:hover:bg-zinc-800 transition-colors duration-300">
          {copying ? <Check size={16} className="text-emerald-500" /> : <Clipboard size={16} />}
          {copying ? 'Copied' : 'Copy Plan'}
        </button>
        <button onClick={handleSave} className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-300 dark:border-zinc-700 text-slate-700 dark:text-slate-300 text-sm font-medium hover:bg-slate-100 dark:hover:bg-zinc-800 transition-colors duration-300">
          {saving ? <Check size={16} className="text-emerald-500" /> : <Save size={16} />}
          {saving ? 'Saved' : 'Save Plan'}
        </button>
      </div>
    </div>
  )
}

export default ExportPlan
